---
- hosts: 172.31.18.146
  become: yes
  tasks:
  - name: install git
    apt: 
      name: git
      states: present
    tags: mygit

  - name: install tree
    apt: 
      name: tree
      states: present
    tags: mytree 

  - name: install wget
    apt: 
      name: wget
      states: present
    tags: mygit


